version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  publisher:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: Services/Publisher/Dockerfile

  subscriber:
    image: ${DOCKER_REGISTRY-}subscriber
    build:
      context: .
      dockerfile: Services/Subscriber/Dockerfile


  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: ApiGateways/Aggregator/Dockerfile

volumes:
  portainer_data:
